FROM nginx:latest
WORKDIR /usr/share/nginx/html
COPY html-template .
#git clone https://github.com/jestrade/html-template

#alternativa, ¿pero se necesita un repositorio para que corra
#FROM nginx:latest
#WORKDIR /usr/share/nginx/html
#RUN git clone https://github.com/jestrade/html-template . #trae imagen desde el repositorio y lo deja en . (el WORKDIR de la línea anterior)
